# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24bcf657fa0827b2e85ccbdf5441d0da630322b6f3e20964f265da091ed3c121e7ca12ce861e41bd7651db54c99627ae3fbe49d3ebeea7deb927f4ecd92c5e8f

test:
  secret_key_base: f5077831f60eeb2a457353006d398c20104eadefd06d00a37694fcc6db6d6835e1695c553cab01a33177f8c58a06fd87c195568c9945518cbe9da0d81f0f3af7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
